### ISSUE TITLE
Cannot find module url-join

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel-benchmark-action#25]
https://github.com/parcel-bundler/parcel/pull/5462/checks?check_run_id=1542100126

![Bildschirmfoto 2020-12-12 um 12 25 37](https://user-images.githubusercontent.com/4586894/101982562-25ec1080-3c75-11eb-8b04-8cd771c0e5f1.png)

**Comment by DeMoorJasper** [comment]
@mischnic thanks for reporting this, didn't know run also ran the clean command, that's pretty weird.

Reworked the commands to not run clean....
